CON-1199 workflows module should depend on the enclave using the runtimeOnly keyword
Before this commit, the workflows module would depend on the enclave module as compile and would throw the exception:

java.lang.IllegalStateException: Multiple enclaves were found: [graalvm debug com.r3.conclave.cordapp.sample.enclave.ReverseEnclave, graalvm debug com.r3.conclave.cordapp.sample.enclave.ReverseEnclave]

The hello-world also uses runtimeOnly keyword instead of compile/